### ISSUE TITLE
v6 endpoint can't handle multiple v5 subscriptions for the same message type

### ISSUE THREAD

**Issue by christoffer-lundqvist** [Particular/NServiceBus.Persistence.Sql#117]
A V6 publisher endpoint puts subscriptions on error queue when handling multiple subscriptions from a v5 endpoint for same message type.
```
 public interface IProductImportedEvent : IInteriorEvent
  {
    Guid ProductId { get; set; }
}
```

We have multiple handlers for this message for a v5 endpoint.

The v6 endpoint is using NServiceBus.Persistence.Sql" version="2.0.1"
MSMQ transport

We also have enabled retries.
```
recoverability.Immediate(...
recoverability.Delayed(...
```
**Exception:**
```
declare @dummy int;
merge [dbo].[ncgOrder_Service_SubscriptionData] with (holdlock) as target
using(select @Endpoint as Endpoint, @Subscriber as Subscriber, @MessageType as MessageType) as source
on target.Endpoint = source.Endpoint and
   target.Subscriber = source.Subscriber and
   target.MessageType = source.MessageType
when matched then
    update set @dummy = 0
when not matched then
insert
(
    Subscriber,
    MessageType,
    Endpoint,
    PersistenceVersion
)
values
(
    @Subscriber,
    @MessageType,
    @Endpoint,
    @PersistenceVersion
);</Value>
	</HeaderInfo>
	<HeaderInfo>
		<Key>NServiceBus.ExceptionInfo.Source</Key>
		<Value>NServiceBus.Persistence.Sql</Value>
	</HeaderInfo>
	<HeaderInfo>
		<Key>NServiceBus.ExceptionInfo.StackTrace</Key>
		<Value>System.Exception: Failed to ExecuteNonQuery. CommandText:

declare @dummy int;
merge [dbo].[ncgOrder_Service_SubscriptionData] with (holdlock) as target
using(select @Endpoint as Endpoint, @Subscriber as Subscriber, @MessageType as MessageType) as source
on target.Endpoint = source.Endpoint and
   target.Subscriber = source.Subscriber and
   target.MessageType = source.MessageType
when matched then
    update set @dummy = 0
when not matched then
insert
(
    Subscriber,
    MessageType,
    Endpoint,
    PersistenceVersion
)
values
(
    @Subscriber,
    @MessageType,
    @Endpoint,
    @PersistenceVersion
); ---&gt; System.Data.SqlClient.SqlException: Violation of PRIMARY KEY constraint 'PK__ncgOrder__A745BB0A6BEC9A77'. Cannot insert duplicate key in object 'dbo.ncgOrder_Service_SubscriptionData'. The duplicate key value is (NcgPlus.Service@xxxxxxxxx, NcgOrder.Service.InternalEvents.Product.IProductImportedEvent).
The statement has been terminated.
   at System.Data.SqlClient.SqlConnection.OnError(SqlException exception, Boolean breakConnection, Action`1 wrapCloseInAction)
   at System.Data.SqlClient.SqlInternalConnection.OnError(SqlException exception, Boolean breakConnection, Action`1 wrapCloseInAction)
   at System.Data.SqlClient.TdsParser.ThrowExceptionAndWarning(TdsParserStateObject stateObj, Boolean callerHasConnectionLock, Boolean asyncClose)
   at System.Data.SqlClient.TdsParser.TryRun(RunBehavior runBehavior, SqlCommand cmdHandler, SqlDataReader dataStream, BulkCopySimpleResultSet bulkCopyHandler, TdsParserStateObject stateObj, Boolean&amp; dataReady)
   at System.Data.SqlClient.SqlCommand.FinishExecuteReader(SqlDataReader ds, RunBehavior runBehavior, String resetOptionsString, Boolean isInternal, Boolean forDescribeParameterEncryption)
   at System.Data.SqlClient.SqlCommand.CompleteAsyncExecuteReader(Boolean isInternal, Boolean forDescribeParameterEncryption)
   at System.Data.SqlClient.SqlCommand.InternalEndExecuteNonQuery(IAsyncResult asyncResult, String endMethod, Boolean isInternal)
   at System.Data.SqlClient.SqlCommand.EndExecuteNonQueryInternal(IAsyncResult asyncResult)
   at System.Data.SqlClient.SqlCommand.EndExecuteNonQueryAsync(IAsyncResult asyncResult)
```

**Comment by andreasohlund** [comment]
@christoffer-lundqvist you're running the endpoint with MaxConcurrency == 1 right?

**Comment by christoffer-lundqvist** [comment]
Yes. 

Skickat från min iPhone

**Comment by DavidBoike** [comment]
I have replicated this in a test and am preparing a fix. This is thanks to MS SQL's glorious (mis)handling of `A = null` vs. `A is null`.

The good news @christoffer-lundqvist is that for each of the subscription messages that goes to the error queue was trying to ensure a subscription that already exists, so events will get sent to the correct subscribers.

**Comment by SzymonPobiega** [comment]
@DavidBoike do I understand correctly that there is **no** message loss possibility due to this bug?

**Comment by DavidBoike** [comment]
Correct, it presents as following:

1. First subscription request shows up (with null endpoint) and is stored
2. Endpoint is restarted and sends new subscription request
3. Merge statement's where clause incorrectly thinks null != null, attempts to insert, and fails from PK violation
4. Database still correctly shows 1 subscription

**Comment by weralabaj** [comment]
@christoffer-lundqvist we're preparing a patch, just wanted to confirm - will it be ok for you to upgrade to 2.1.3?

**Comment by christoffer-lundqvist** [comment]
Sure.

**Comment by SzymonPobiega** [comment]
@christoffer-lundqvist 2.1.3 is now released.

**Comment by christoffer-lundqvist** [comment]
Thanks. We will start testing this right away!

**Comment by weralabaj** [comment]
@christoffer-lundqvist Can you let us know if the patch resolved your issue?

**Comment by christoffer-lundqvist** [comment]
It is working. Thanks!

**Comment by weralabaj** [comment]
Awesome, thank you!
