### ISSUE TITLE
ISqlStorageSession.Connection is null in constructor

### ISSUE THREAD

**Issue by pardahlman** [Particular/NServiceBus.Persistence.Sql#1188]
#### Description

When `ISqlStorageSession` is resolved as part of the dependency graph of a `IMessageHandler<>` the `ISqlStorageSession.Connection` is null in the constructor. This makes it impossible to perform SQL calls in the constructor that is part of the outbox transaction.

Our setup uses the `TransactionScope` mode for the outbox and when trying to open a new connection if fails with the following exception:

```
System.PlatformNotSupportedException: This platform does not support distributed transactions.
   at System.Transactions.Distributed.DistributedTransactionManager.GetDistributedTransactionFromTransmitterPropagationToken(Byte[] propagationToken)
   at System.Transactions.TransactionInterop.GetDistributedTransactionFromTransmitterPropagationToken(Byte[] propagationToken)
```

This makes me believe that the outbox connection is in fact open but not yet assigned to the `ISqlStorageSession` instance.

I realize that it is a uncommon scenario, but we have legacy code with this behavior. It is also complicated to migrate/use this code in a message handler.

#### Expected behavior

Injected `ISqlStorageSession.Connection` is not null in any domain code resolved as part of a message handler, including constructor.

#### Actual behavior

Injected `ISqlStorageSession.Connection` is null when the constructor of injected service is resolved.

#### Versions

`NServiceBus.Persistence.Sql` 7.0.0

### Steps to reproduce

Configure endpoint to use SQL persistence and activate outbox. Inject `ISqlStorageSession` in message handler and debug/inspect `ISqlStorageSession.Connection`.

**Comment by pardahlman** [comment]
Hi @danielmarbach,

Thanks for taking the time to investigate this and pointing me in the right direction 🙏  I found the culprit: a singleton registration, just as you suspected.

Closing this issue.
