### ISSUE TITLE
Using Ninject results in failing start: Unhandled Exception: Ninject.ActivationException: Error activating IntPtr

### ISSUE THREAD

**Issue by ramonsmits** [Particular/NServiceBus.Persistence.Sql#128]
When configuring Ninject as the object builder you will get the following exception at the start:

```
Unhandled Exception: Ninject.ActivationException: Error activating IntPtr
No matching bindings are available, and the type is not self-bindable.
Activation path:
  3) Injection of dependency IntPtr into parameter method of constructor of type RetrieveVersionSpecificJsonSettings
  2) Injection of dependency RetrieveVersionSpecificJsonSettings into parameter versionSpecificSettings of constructor of type SagaInfoCache
  1) Request for SagaInfoCache

Suggestions:
  1) Ensure that you have defined a binding for IntPtr.
  2) If the binding was defined in a module, ensure that the module has been loaded into the kernel.
  3) Ensure you have not accidentally created more than one kernel.
  4) If you are using constructor arguments, ensure that the parameter name matches the constructors parameter name.
  5) If you are using automatic module loading, ensure the search path and filters are correct.
```

This seems to indicate that with Ninject an incorrect constructor is used or that a registration is missing or maybe that Ninject is not compatible with delegates as constructor arguments?

## Init code

```c#
var endpointConfiguration = new EndpointConfiguration("Samples.SQLNHibernateOutbox.Receiver");

var persistence = endpointConfiguration.UsePersistence<SqlPersistence>();
persistence.SqlVariant(SqlVariant.MsSqlServer);
persistence.ConnectionBuilder(connectionBuilder: () => new SqlConnection(ConnectionStrings.PersistenceConnection));

var subscriptions = persistence.SubscriptionSettings();
subscriptions.CacheFor(TimeSpan.FromMinutes(1));

endpointConfiguration.SendFailedMessagesTo("error");
endpointConfiguration.UseContainer<NinjectBuilder>();

var endpointInstance = await Endpoint.Start(endpointConfiguration);
```

## Involved types

```c#
public delegate JsonSerializerSettings RetrieveVersionSpecificJsonSettings(Type sagaDataType, Version sagaVersion);
```
- https://github.com/Particular/NServiceBus.Persistence.Sql/blob/develop/src/SqlPersistence/Saga/Serialization/RetrieveVersionSpecificJsonSettings.cs#L12

```c#
    public SagaInfoCache(
        RetrieveVersionSpecificJsonSettings versionSpecificSettings,
        JsonSerializer jsonSerializer,
        Func<TextReader, JsonReader> readerCreator,
        Func<TextWriter, JsonWriter> writerCreator,
        SagaCommandBuilder commandBuilder,
        string tablePrefix,
        string schema,
        SqlVariant sqlVariant,
        SagaMetadataCollection metadataCollection,
        Func<string, string> nameFilter)
```
- https://github.com/Particular/NServiceBus.Persistence.Sql/blob/2.1.3/src/SqlPersistence/Saga/SagaInfoCache.cs#L23-L34

## Package info

```xml
<?xml version="1.0" encoding="utf-8"?>
<packages>
  <package id="Newtonsoft.Json" version="10.0.3" targetFramework="net452" />
  <package id="Ninject" version="3.2.2.0" targetFramework="net452" />
  <package id="Ninject.Extensions.ContextPreservation" version="3.2.0.0" targetFramework="net452" />
  <package id="Ninject.Extensions.NamedScope" version="3.2.0.0" targetFramework="net452" />
  <package id="NServiceBus" version="6.3.4" targetFramework="net452" />
  <package id="NServiceBus.Ninject" version="6.0.0" targetFramework="net452" />
  <package id="NServiceBus.Persistence.Sql" version="2.1.3" targetFramework="net452" />
  <package id="NServiceBus.Persistence.Sql.MsBuild" version="2.1.3" targetFramework="net452" developmentDependency="true" />
</packages>
```

## Exception info
```
Unhandled Exception: Ninject.ActivationException: Error activating IntPtr
No matching bindings are available, and the type is not self-bindable.
Activation path:
  3) Injection of dependency IntPtr into parameter method of constructor of type RetrieveVersionSpecificJsonSettings
  2) Injection of dependency RetrieveVersionSpecificJsonSettings into parameter versionSpecificSettings of constructor of type SagaInfoCache
  1) Request for SagaInfoCache

Suggestions:
  1) Ensure that you have defined a binding for IntPtr.
  2) If the binding was defined in a module, ensure that the module has been loaded into the kernel.
  3) Ensure you have not accidentally created more than one kernel.
  4) If you are using constructor arguments, ensure that the parameter name matches the constructors parameter name.
  5) If you are using automatic module loading, ensure the search path and filters are correct.

   at Ninject.KernelBase.Resolve(IRequest request)
   at Ninject.Planning.Targets.Target`1.GetValue(Type service, IContext parent)
   at Ninject.Planning.Targets.Target`1.ResolveWithin(IContext parent)
   at Ninject.Activation.Providers.StandardProvider.GetValue(IContext context, ITarget target)
   at Ninject.Activation.Providers.StandardProvider.<>c__DisplayClass4.<Create>b__2(ITarget target)
   at System.Linq.Enumerable.WhereSelectArrayIterator`2.MoveNext()
   at System.Linq.Buffer`1..ctor(IEnumerable`1 source)
   at System.Linq.Enumerable.ToArray[TSource](IEnumerable`1 source)
   at Ninject.Activation.Providers.StandardProvider.Create(IContext context)
   at Ninject.Activation.Context.ResolveInternal(Object scope)
   at Ninject.Activation.Context.Resolve()
   at Ninject.KernelBase.<>c__DisplayClass15.<Resolve>b__f(IBinding binding)
   at System.Linq.Enumerable.WhereSelectEnumerableIterator`2.MoveNext()
   at System.Linq.Enumerable.SingleOrDefault[TSource](IEnumerable`1 source)
   at Ninject.Planning.Targets.Target`1.GetValue(Type service, IContext parent)
   at Ninject.Planning.Targets.Target`1.ResolveWithin(IContext parent)
   at Ninject.Activation.Providers.StandardProvider.GetValue(IContext context, ITarget target)
   at Ninject.Activation.Providers.StandardProvider.<>c__DisplayClass4.<Create>b__2(ITarget target)
   at System.Linq.Enumerable.WhereSelectArrayIterator`2.MoveNext()
   at System.Linq.Buffer`1..ctor(IEnumerable`1 source)
   at System.Linq.Enumerable.ToArray[TSource](IEnumerable`1 source)
   at Ninject.Activation.Providers.StandardProvider.Create(IContext context)
   at Ninject.Activation.Context.ResolveInternal(Object scope)
   at Ninject.Activation.Context.Resolve()
   at Ninject.KernelBase.<>c__DisplayClass15.<Resolve>b__f(IBinding binding)
   at System.Linq.Enumerable.WhereSelectListIterator`2.MoveNext()
   at System.Linq.Enumerable.<CastIterator>d__94`1.MoveNext()
   at System.Linq.Enumerable.SingleOrDefault[TSource](IEnumerable`1 source)
   at StorageSessionFeature.GetInfoCache(IBuilder builder) in C:\BuildAgent\work\a145ee7c8f380d92\src\SqlPersistence\SynchronizedStorage\StorageSessionFeature.cs:line 19
   at StorageSessionFeature.<>c__DisplayClass0_0.<Setup>b__1(IBuilder builder) in C:\BuildAgent\work\a145ee7c8f380d92\src\SqlPersistence\SynchronizedStorage\StorageSessionFeature.cs:line 14
   at NServiceBus.CommonObjectBuilder.<>c__DisplayClass12_0`1.<ConfigureComponent>b__0() in C:\BuildAgent\work\3206e2123f54fce4\src\NServiceBus.Core\ObjectBuilder\Common\CommonObjectBuilder.cs:line 74
   at NServiceBus.ObjectBuilder.Ninject.NinjectObjectBuilder.<>c__DisplayClass17_0`1.<BindComponentToMethod>b__2(IContext context) in C:\Build\src\NServiceBus.Ninject\NinjectObjectBuilder.cs:line 257
   at Ninject.Activation.Providers.CallbackProvider`1.CreateInstance(IContext context)
   at Ninject.Activation.Provider`1.Create(IContext context)
   at Ninject.Activation.Context.ResolveInternal(Object scope)
   at Ninject.Activation.Context.Resolve()
   at Ninject.KernelBase.<>c__DisplayClass15.<Resolve>b__f(IBinding binding)
   at System.Linq.Enumerable.WhereSelectEnumerableIterator`2.MoveNext()
   at System.Linq.Enumerable.Single[TSource](IEnumerable`1 source)
   at NServiceBus.ObjectBuilder.Ninject.NinjectObjectBuilder.Build(Type typeToBuild) in C:\Build\src\NServiceBus.Ninject\NinjectObjectBuilder.cs:line 52
   at NServiceBus.CommonObjectBuilder.Build[T]() in C:\BuildAgent\work\3206e2123f54fce4\src\NServiceBus.Core\ObjectBuilder\Common\CommonObjectBuilder.cs:line 28
   at NServiceBus.Features.ReceiveFeature.<>c__DisplayClass1_0.<Setup>b__3(IBuilder b) in C:\BuildAgent\work\3206e2123f54fce4\src\NServiceBus.Core\Pipeline\Incoming\ReceiveFeature.cs:line 36
   at NServiceBus.CommonObjectBuilder.<>c__DisplayClass12_0`1.<ConfigureComponent>b__0() in C:\BuildAgent\work\3206e2123f54fce4\src\NServiceBus.Core\ObjectBuilder\Common\CommonObjectBuilder.cs:line 74
   at NServiceBus.ObjectBuilder.Ninject.NinjectObjectBuilder.<>c__DisplayClass17_0`1.<BindComponentToMethod>b__2(IContext context) in C:\Build\src\NServiceBus.Ninject\NinjectObjectBuilder.cs:line 257
   at Ninject.Activation.Providers.CallbackProvider`1.CreateInstance(IContext context)
   at Ninject.Activation.Provider`1.Create(IContext context)
   at Ninject.Activation.Context.ResolveInternal(Object scope)
   at Ninject.Activation.Context.Resolve()
   at Ninject.KernelBase.<>c__DisplayClass15.<Resolve>b__f(IBinding binding)
   at System.Linq.Enumerable.WhereSelectEnumerableIterator`2.MoveNext()
   at System.Linq.Enumerable.Single[TSource](IEnumerable`1 source)
   at NServiceBus.ObjectBuilder.Ninject.NinjectObjectBuilder.Build(Type typeToBuild) in C:\Build\src\NServiceBus.Ninject\NinjectObjectBuilder.cs:line 52
   at NServiceBus.CommonObjectBuilder.Build[T]() in C:\BuildAgent\work\3206e2123f54fce4\src\NServiceBus.Core\ObjectBuilder\Common\CommonObjectBuilder.cs:line 28
   at NServiceBus.Features.ReceiveFeature.<>c.<Setup>b__1_1(IBuilder b) in C:\BuildAgent\work\3206e2123f54fce4\src\NServiceBus.Core\Pipeline\Incoming\ReceiveFeature.cs:line 21
   at NServiceBus.Pipeline.PipelineSettings.<>c__DisplayClass8_0`1.<Register>b__0(IBuilder b) in C:\BuildAgent\work\3206e2123f54fce4\src\NServiceBus.Core\Pipeline\PipelineSettings.cs:line 132
   at NServiceBus.Pipeline.RegisterStep.CreateBehavior(IBuilder defaultBuilder) in C:\BuildAgent\work\3206e2123f54fce4\src\NServiceBus.Core\Pipeline\RegisterStep.cs:line 153
   at NServiceBus.Pipeline`1.<>c__DisplayClass0_0.<.ctor>b__1(RegisterStep r) in C:\BuildAgent\work\3206e2123f54fce4\src\NServiceBus.Core\Pipeline\Pipeline.cs:line 26
   at System.Linq.Enumerable.WhereSelectListIterator`2.MoveNext()
   at System.Linq.Buffer`1..ctor(IEnumerable`1 source)
   at System.Linq.Enumerable.ToArray[TSource](IEnumerable`1 source)
   at NServiceBus.Pipeline`1..ctor(IBuilder builder, ReadOnlySettings settings, PipelineModifications pipelineModifications) in C:\BuildAgent\work\3206e2123f54fce4\src\NServiceBus.Core\Pipeline\Pipeline.cs:line 25
   at NServiceBus.StartableEndpoint.<Start>d__1.MoveNext() in C:\BuildAgent\work\3206e2123f54fce4\src\NServiceBus.Core\StartableEndpoint.cs:line 38
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at NServiceBus.Endpoint.<Start>d__1.MoveNext() in C:\BuildAgent\work\3206e2123f54fce4\src\NServiceBus.Core\Endpoint.cs:line 28
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.ConfiguredTaskAwaitable`1.ConfiguredTaskAwaiter.GetResult()
   at Program.<AsyncMain>d__1.MoveNext() in C:\Users\ramon\src\vahid8261\SampleOutbox-Nhibernate\Reciever\Program.cs:line 90
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.GetResult()
   at Program.Main() in C:\Users\ramon\src\vahid8261\SampleOutbox-Nhibernate\Reciever\Program.cs:line 22
```

## References

- https://eu1.salesforce.com/apex/Case?num=00029172

**Comment by ramonsmits** [comment]
@Particular/sqlpersistence-maintainers @Particular/container-maintainers I'm not sure about the cause but I think it is due to the usage of a delegate.

**Comment by DavidBoike** [comment]
Since it works with other containers, wouldn't it make more sense to approach this as a bug in the Ninject adapter?

**Comment by ramonsmits** [comment]
I leave that up to the maintainers to decide. I think it requires SQL persistence to comply to the rules of Ninject.

**Comment by mauroservienti** [comment]
I'll have a look at this hopefully tomorrow morning

**Comment by SimonCropp** [comment]
@ramonsmits i cant replicate this. can u share the solution?

**Comment by SimonCropp** [comment]
@ramonsmits repro:
[NinjectSqlPersistenceIssue.7z.txt](https://github.com/Particular/NServiceBus.Persistence.Sql/files/1168527/NinjectSqlPersistenceIssue.7z.txt)
