### ISSUE TITLE
Assembly.GetEntryAssembly() used in the ScriptFinder can throw an exception

### ISSUE THREAD

**Issue by janpieterz** [Particular/NServiceBus.Persistence.Sql#179]
This seems to occur, for example, when loading from NServiceBus.Host. Will anyway be moving away from NServiceBus.Host here since it's being deprecated, but one can imagine other self hosting scenario's that'd be operating under similar circumstances.

```
System.NullReferenceException: Object reference not set to an instance of an object.
   at ScriptLocation.FindScriptDirectory(SqlDialect dialect)
   at InstallerFeature.Setup(FeatureConfigurationContext context)
   at NServiceBus.Features.FeatureActivator.ActivateFeature(FeatureInfo featureInfo, List`1 featuresToActivate, IConfigureComponents container, PipelineSettings pipelineSettings, RoutingComponent routing)
   at NServiceBus.Features.FeatureActivator.SetupFeatures(IConfigureComponents container, PipelineSettings pipelineSettings, RoutingComponent routing)
   at NServiceBus.InitializableEndpoint.<Initialize>d__1.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at NServiceBus.GenericHost.<Start>d__1.MoveNext() in C:\BuildAgent\work\fc89e968acb99302\src\NServiceBus.Hosting.Windows\GenericHost.cs:line 47
```

**Comment by SimonCropp** [comment]
@janpieterz i can see how this can be a problem. i have seen GetEntryAssembly return null in certain scenarios. and i have a plan to fix it. But i am having trouble reproducing this. would i be possible for you to upload a small solution that causes the problem to manifest. this way we can be certain that any change we make actually will fix your problem

**Comment by janpieterz** [comment]
@SimonCropp understood. This repo throws the error here:
https://github.com/janpieterz/NSBTestHostException

**Comment by SimonCropp** [comment]
@janpieterz 3.0.0-alpha0005 is on myget and should fix this for you

**Comment by SimonCropp** [comment]
So sorry. i stuffed up on the versioning. The new package version is 3.0.0-beta4

**Comment by janpieterz** [comment]
No worries! Just updated and confirmed here 😄
