### ISSUE TITLE
Custom Saga finding logic for IAmStartedByMessage throws exception

### ISSUE THREAD

**Issue by macdonald-keith-vmware** [Particular/NServiceBus.Persistence.Sql#212]
NSB 6.3.4
Persistence.Sql 2.1.3, MS Sql Server persistence
RabbitMQ 4.3.2

I implemented an IFindSagas<MySagaData>.Using<MyStartCommand> for custom saga finding logic. This works fine if the message being references is for IHandleMessage within the saga. However, if the message is for IAmStartedBy, then several issues occur.

1.  The property used for correlation in the SagaData is not populated. This is easily alleviated by doing the assignment manually. I'm not sure if there can be a resolution for this. 

2. When the IAmStartedBy handler has finished, and the saga is attempted to be persisted, an exception is thrown. This makes it appear that other properties are not being set/managed either.

This can be easily reproduced by using the sample code for saga finding logic on the Particular website (https://docs.particular.net/samples/saga/sql-sagafinder/) and changing the custom finding logic to work for the StartOrder message instead of the CompletePaymentTransaction message.
```
==========================================
System.Exception: Failed to ExecuteNonQuery. CommandText:

insert into [NServiceBus].[mySaga]
(
Id,
Metadata,
Data,
PersistenceVersion,
SagaTypeVersion,
Concurrency,
Correlation_OperationId
)
values
(
@Id,
@Metadata,
@Data,
@PersistenceVersion,
@SagaTypeVersion,
1,
@CorrelationId
) ---> System.Data.SqlClient.SqlException: Must declare the scalar variable "@CorrelationId".
at System.Data.SqlClient.SqlConnection.OnError(SqlException exception, Boolean breakConnection, Action`1 wrapCloseInAction)
   at System.Data.SqlClient.SqlInternalConnection.OnError(SqlException exception, Boolean breakConnection, Action`1 wrapCloseInAction)
   at System.Data.SqlClient.TdsParser.ThrowExceptionAndWarning(TdsParserStateObject stateObj, Boolean callerHasConnectionLock, Boolean asyncClose)
   at System.Data.SqlClient.TdsParser.TryRun(RunBehavior runBehavior, SqlCommand cmdHandler, SqlDataReader dataStream, BulkCopySimpleResultSet bulkCopyHandler, TdsParserStateObject stateObj, Boolean& dataReady)
   at System.Data.SqlClient.SqlCommand.FinishExecuteReader(SqlDataReader ds, RunBehavior runBehavior, String resetOptionsString, Boolean isInternal, Boolean forDescribeParameterEncryption)
   at System.Data.SqlClient.SqlCommand.CompleteAsyncExecuteReader(Boolean isInternal, Boolean forDescribeParameterEncryption)
   at System.Data.SqlClient.SqlCommand.InternalEndExecuteNonQuery(IAsyncResult asyncResult, String endMethod, Boolean isInternal)
   at System.Data.SqlClient.SqlCommand.EndExecuteNonQueryInternal(IAsyncResult asyncResult)
   at System.Data.SqlClient.SqlCommand.EndExecuteNonQueryAsync(IAsyncResult asyncResult)
   at System.Threading.Tasks.TaskFactory`1.FromAsyncCoreLogic(IAsyncResult iar, Func`2 endFunction, Action`1 endAction, Task`1 promise, Boolean requiresSynchronization)
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Extensions.<ExecuteNonQueryEx>d__7.MoveNext() in C:\BuildAgent\work\a145ee7c8f380d92\src\SqlPersistence\Extensions.cs:line 75
   --- End of inner exception stack trace ---
   at Extensions.<ExecuteNonQueryEx>d__7.MoveNext() in C:\BuildAgent\work\a145ee7c8f380d92\src\SqlPersistence\Extensions.cs:line 80
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at SagaPersister.<Save>d__19.MoveNext() in C:\BuildAgent\work\a145ee7c8f380d92\src\SqlPersistence\Saga\SagaPersister_Save.cs:line 44
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd(Task task)
   at NServiceBus.SagaPersistenceBehavior.<Invoke>d__1.MoveNext() in C:\BuildAgent\work\3206e2123f54fce4\src\NServiceBus.Core\Sagas\SagaPersistenceBehavior.cs:line 166
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at NServiceBus.LoadHandlersConnector.<Invoke>d__1.MoveNext() in C:\BuildAgent\work\3206e2123f54fce4\src\NServiceBus.Core\Pipeline\Incoming\LoadHandlersConnector.cs:line 40
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at NServiceBus.InvokeSagaNotFoundBehavior.<Invoke>d__0.MoveNext() in C:\BuildAgent\work\3206e2123f54fce4\src\NServiceBus.Core\Sagas\InvokeSagaNotFoundBehavior.cs:line 16
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.ConfiguredTaskAwaitable.ConfiguredTaskAwaiter.GetResult()
   at Panagora.Framework.Common.ServiceBus.DeserializeConnector.<Invoke>d__5.MoveNext() in C:\src\Main\Framework\Panagora.Framework.Common.ServiceBus\Serialization\DeserializeConnector.cs:line 63
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at ReceivePerformanceDiagnosticsBehavior.<Invoke>d__0.MoveNext() in C:\BuildAgent\work\62a1a7ae466302a5\src\NServiceBus.Metrics\ProbeBuilders\ReceivePerformanceDiagnosticsBehavior.cs:line 18
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at NServiceBus.InvokeAuditPipelineBehavior.<Invoke>d__1.MoveNext() in C:\BuildAgent\work\3206e2123f54fce4\src\NServiceBus.Core\Audit\InvokeAuditPipelineBehavior.cs:line 18
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at NServiceBus.ProcessingStatisticsBehavior.<Invoke>d__0.MoveNext() in C:\BuildAgent\work\3206e2123f54fce4\src\NServiceBus.Core\Performance\Statistics\ProcessingStatisticsBehavior.cs:line 27
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at NServiceBus.TransportReceiveToPhysicalMessageProcessingConnector.<Invoke>d__1.MoveNext() in C:\BuildAgent\work\3206e2123f54fce4\src\NServiceBus.Core\Pipeline\Incoming\TransportReceiveToPhysicalMessageProcessingConnector.cs:line 37
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at NServiceBus.MainPipelineExecutor.<Invoke>d__1.MoveNext() in C:\BuildAgent\work\3206e2123f54fce4\src\NServiceBus.Core\Pipeline\MainPipelineExecutor.cs:line 32
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd(Task task)
   at NServiceBus.Transport.RabbitMQ.MessagePump.<Process>d__29.MoveNext() in C:\BuildAgent\work\ef98ad7376e3379a\src\NServiceBus.RabbitMQ\Receiving\MessagePump.cs:line 248
```

**Comment by SzymonPobiega** [comment]
@macdonald-keith-vmware I could not reproduce this behavior. I took the sample and did following changes:

### Finder

```
class OrderSagaFinder : IFindSagas<OrderSagaData>.Using<StartOrder>
{
    public Task<OrderSagaData> FindBy(StartOrder message, SynchronizedStorageSession session, ReadOnlyContextBag context)
    {
        return session.GetSagaData<OrderSagaData>(
            context: context,
            whereClause: "1 = 0",
            appendParameters: (builder, append) =>
            {
            });
    }
}
```

Ensures always a new saga instance is created

### Saga

```
public Task Handle(StartOrder message, IMessageHandlerContext context)
{
    Data.OrderId = message.OrderId;
```

Ensures that correlation property is assigned. Otherwise the validation throws an exception

I also removed the mapping for the `StartOrder` message.

### Request handler

class IssuePaymentRequestHandler : IHandleMessages<IssuePaymentRequest>
{
    public Task Handle(IssuePaymentRequest message, IMessageHandlerContext context)
    {
        var completePayment = new CompletePaymentTransaction
        {
            PaymentTransactionId = message.PaymentTransactionId
        };
        return context.Reply(completePayment);
    }
}

I've changed `SendLocal` to `Reply` so that the complete payment message does not have to be correlated (it will contain the saga ID).

After doing these changes the samples works as expected.

**Comment by SzymonPobiega** [comment]
@macdonald-keith-vmware I noticed, though, that it fails with the exception you described if I remove all the mappings but leave the correlation property set in the saga definition. In case your saga does not use correlation, it should be defined as `null`

```
protected override string CorrelationPropertyName => null;
```

That said, we should have code that verifies this assumption.

**Comment by SzymonPobiega** [comment]
FYI #213 adds the messing validation rule

**Comment by macdonald-keith-vmware** [comment]
Yes, I did assign a value to the CorrelationPropertyName value. 

Is that property only used for start messages to assign a value to the SagaData? If this property isn't filled in, doesn't it mean that every message handled by the saga would need custom finding logic?

**Comment by DavidBoike** [comment]
@macdonald-keith-vmware The correlation property isn't only used for start messages. It's meant to be the primary lookup for how you find saga data given an incoming message. The SagaId primary key is going to be a random Guid and useless for any lookups except for two special cases:

1. The saga requests a timeout. The timeout message has the SagaId built in as a header, so it can be used to look up the saga by its primary key
2. The saga sends a command to an external handler (including the SagaId in a header) and the handler replies back to the saga - the handler mirrors that SagaId back in the reply.

With any other type of message, you need a way to find the saga data from the incoming message. This means either using the CorrelationId, or supplying a custom finder.

So yes, if you specify a null CorrelationId, you'll have to have custom finding logic for every message type not covered by the 2 cases above.

Does that help?

**Comment by weralabaj** [comment]
@macdonald-keith-vmware We added a validation rule that gives a more explicit error message. I hope that makes it easier to deal with such issues.

If you think there's still more we could do to help, please, reopen the issue.
