### ISSUE TITLE
Concurrent connections in same TransactionScope throw Exceptions

### ISSUE THREAD

**Issue by timbussmann** [Particular/NServiceBus.Persistence.Sql#260]
When trying to publish a set of events via `IMessageSession` in a concurrency optimized loop like this:

```
using (var tx = new TransactionScope(TransactionScopeAsyncFlowOption.Enabled))
{
    List<Task> tasks = new List<Task>(nom);
    for (int i = 0; i < 10; i++)
    {
             tasks.Add(endpoint.Publish(new SampleEvent()));
    }

    await Task.WhenAll(tasks);
    tx.Complete();
}
```

the transaction fails with an exception:

> Transaction context in use by another session.
   at System.Data.SqlClient.SqlConnection.OnError(SqlException exception, Boolean breakConnection, Action`1 wrapCloseInAction)
   at System.Data.SqlClient.SqlInternalConnection.OnError(SqlException exception, Boolean breakConnection, Action`1 wrapCloseInAction)
   at System.Data.SqlClient.TdsParser.ThrowExceptionAndWarning(TdsParserStateObject stateObj, Boolean callerHasConnectionLock, Boolean asyncClose)
   at System.Data.SqlClient.TdsParser.TryRun(RunBehavior runBehavior, SqlCommand cmdHandler, SqlDataReader dataStream, BulkCopySimpleResultSet bulkCopyHandler, TdsParserStateObject stateObj, Boolean& dataReady)
   at System.Data.SqlClient.TdsParser.Run(RunBehavior runBehavior, SqlCommand cmdHandler, SqlDataReader dataStream, BulkCopySimpleResultSet bulkCopyHandler, TdsParserStateObject stateObj)
   at System.Data.SqlClient.TdsParser.TdsExecuteTransactionManagerRequest(Byte[] buffer, TransactionManagerRequestType request, String transactionName, TransactionManagerIsolationLevel isoLevel, Int32 timeout, SqlInternalTransaction transaction, TdsParserStateObject stateObj, Boolean isDelegateControlRequest)
   at System.Data.SqlClient.SqlInternalConnectionTds.PropagateTransactionCookie(Byte[] cookie)
   at System.Data.SqlClient.SqlInternalConnection.EnlistNonNull(Transaction tx)
   at System.Data.SqlClient.SqlInternalConnection.Enlist(Transaction tx)
   at System.Data.SqlClient.SqlInternalConnectionTds.Activate(Transaction transaction)
   at System.Data.ProviderBase.DbConnectionInternal.ActivateConnection(Transaction transaction)
   at System.Data.ProviderBase.DbConnectionPool.PrepareConnection(DbConnection owningObject, DbConnectionInternal obj, Transaction transaction)
   at System.Data.ProviderBase.DbConnectionPool.TryGetConnection(DbConnection owningObject, UInt32 waitForMultipleObjectsTimeout, Boolean allowCreate, Boolean onlyOneCheckConnection, DbConnectionOptions userOptions, DbConnectionInternal& connection)
   at System.Data.ProviderBase.DbConnectionPool.WaitForPendingOpen()

Configuration used:
* SQL Transport
* SQL Persistence (both on the same MSSQL Server)
  * Disabled subscription caching
* 1 subscriber subscribed to the published event

As each publish operations opens a connection to query the subscriptions and to insert the published messages concurrently, the transaction will be promoted to the DTC. The concurrent connections seem to cause issues with the enlistment though as also pointed out by this article: https://blogs.msdn.microsoft.com/asiatech/2009/08/09/system-transaction-may-fail-in-multiple-thread-environment

I wasn't able to reproduce the exception when using sends instead of published (not hitting the subscription storage).

Workarounds:
* Avoid concurrent publishes (awaiting each publish immediately)
* Avoid wrapping the publishes in a TransactionScope
* Move the concurrent publishes into a message handler and trigger the message handler by a dedicated message.

**Comment by timbussmann** [comment]
Note that the errors can also be reproduced even without involvement of any NServiceBus code. E.g.

```
using (var tx = new TransactionScope(TransactionScopeAsyncFlowOption.Enabled))
{
    List<Task> tasks = new List<Task>();
    for (int i = 0; i < 5; i++)
    {
        var con = new SqlConnection(ConnectionString);
        con.Open();

        var cmd1 = new SqlCommand($"SELECT COUNT({i}) FROM <x>", con, null);
        Task<object> item = Task.Run(() => cmd1.ExecuteScalarAsync());
        tasks.Add(item);
    }

    await Task.WhenAll(tasks);
    tx.Complete();
}
```

also fails.

**Comment by SzymonPobiega** [comment]
This has been, by mistake, addressed by https://github.com/Particular/NServiceBus.Persistence.Sql/issues/276
