### ISSUE TITLE
Is the SqlSagaAttribute really needed to detect the correlation property?

### ISSUE THREAD

**Issue by danielmarbach** [Particular/NServiceBus.Persistence.Sql#40]
I was looking briefly into the saga definition reader and wrote the following simple mapping:

        protected override void ConfigureHowToFindSaga(SagaPropertyMapper<SagaData> mapper)
        {
            mapper.ConfigureMapping<object>(o => null).ToSaga(s => s.Correlation);
            mapper.ConfigureMapping<string>(o => null).ToSaga(s => s.Correlation);
        }

Which produced the following IL method body

```
items = {Mono.Cecil.Cil.Instruction[]} {Mono.Cecil.Cil.Instruction[122]}
 [0] = {Mono.Cecil.Cil.Instruction} {IL_0000: nop}
 [1] = {Mono.Cecil.Cil.Instruction} {IL_0001: ldarg.1}
 [2] = {Mono.Cecil.Cil.Instruction} {IL_0002: ldtoken System.Object}
 [3] = {Mono.Cecil.Cil.Instruction} {IL_0007: call System.Type System.Type::GetTypeFromHandle(System.RuntimeTypeHandle)}
 [4] = {Mono.Cecil.Cil.Instruction} {IL_000c: ldstr "o"}
 [5] = {Mono.Cecil.Cil.Instruction} {IL_0011: call System.Linq.Expressions.ParameterExpression System.Linq.Expressions.Expression::Parameter(System.Type,System.String)}
 [6] = {Mono.Cecil.Cil.Instruction} {IL_0016: stloc.0}
 [7] = {Mono.Cecil.Cil.Instruction} {IL_0017: ldnull}
 [8] = {Mono.Cecil.Cil.Instruction} {IL_0018: ldtoken System.Object}
 [9] = {Mono.Cecil.Cil.Instruction} {IL_001d: call System.Type System.Type::GetTypeFromHandle(System.RuntimeTypeHandle)}
 [10] = {Mono.Cecil.Cil.Instruction} {IL_0022: call System.Linq.Expressions.ConstantExpression System.Linq.Expressions.Expression::Constant(System.Object,System.Type)}
 [11] = {Mono.Cecil.Cil.Instruction} {IL_0027: ldc.i4.1}
 [12] = {Mono.Cecil.Cil.Instruction} {IL_0028: newarr System.Linq.Expressions.ParameterExpression}
 [13] = {Mono.Cecil.Cil.Instruction} {IL_002d: dup}
 [14] = {Mono.Cecil.Cil.Instruction} {IL_002e: ldc.i4.0}
 [15] = {Mono.Cecil.Cil.Instruction} {IL_002f: ldloc.0}
 [16] = {Mono.Cecil.Cil.Instruction} {IL_0030: stelem.ref}
 [17] = {Mono.Cecil.Cil.Instruction} {IL_0031: call System.Linq.Expressions.Expression`1<!!0> System.Linq.Expressions.Expression::Lambda<System.Func`2<System.Object,System.Object>>(System.Linq.Expressions.Expression,System.Linq.Expressions.ParameterExpression[])}
 **[18] = {Mono.Cecil.Cil.Instruction} {IL_0036: callvirt NServiceBus.ToSagaExpression`2<!0,!!0> NServiceBus.SagaPropertyMapper`1<SagaDefinitionReaderTest/SimpleSaga/SagaData>::ConfigureMapping<System.Object>(System.Linq.Expressions.Expression`1<System.Func`2<!!0,System.Object>>)}**
 [19] = {Mono.Cecil.Cil.Instruction} {IL_003b: ldtoken SagaDefinitionReaderTest/SimpleSaga/SagaData}
 [20] = {Mono.Cecil.Cil.Instruction} {IL_0040: call System.Type System.Type::GetTypeFromHandle(System.RuntimeTypeHandle)}
 [21] = {Mono.Cecil.Cil.Instruction} {IL_0045: ldstr "s"}
 [22] = {Mono.Cecil.Cil.Instruction} {IL_004a: call System.Linq.Expressions.ParameterExpression System.Linq.Expressions.Expression::Parameter(System.Type,System.String)}
 [23] = {Mono.Cecil.Cil.Instruction} {IL_004f: stloc.0}
 [24] = {Mono.Cecil.Cil.Instruction} {IL_0050: ldloc.0}
 **[25] = {Mono.Cecil.Cil.Instruction} {IL_0051: ldtoken System.String SagaDefinitionReaderTest/SimpleSaga/SagaData::get_Correlation()}**
 [26] = {Mono.Cecil.Cil.Instruction} {IL_0056: call System.Reflection.MethodBase System.Reflection.MethodBase::GetMethodFromHandle(System.RuntimeMethodHandle)}
 [27] = {Mono.Cecil.Cil.Instruction} {IL_005b: castclass System.Reflection.MethodInfo}
 [28] = {Mono.Cecil.Cil.Instruction} {IL_0060: call System.Linq.Expressions.MemberExpression System.Linq.Expressions.Expression::Property(System.Linq.Expressions.Expression,System.Reflection.MethodInfo)}
 [29] = {Mono.Cecil.Cil.Instruction} {IL_0065: ldc.i4.1}
 [30] = {Mono.Cecil.Cil.Instruction} {IL_0066: newarr System.Linq.Expressions.ParameterExpression}
 [31] = {Mono.Cecil.Cil.Instruction} {IL_006b: dup}
 [32] = {Mono.Cecil.Cil.Instruction} {IL_006c: ldc.i4.0}
 [33] = {Mono.Cecil.Cil.Instruction} {IL_006d: ldloc.0}
 [34] = {Mono.Cecil.Cil.Instruction} {IL_006e: stelem.ref}
 [35] = {Mono.Cecil.Cil.Instruction} {IL_006f: call System.Linq.Expressions.Expression`1<!!0> System.Linq.Expressions.Expression::Lambda<System.Func`2<SagaDefinitionReaderTest/SimpleSaga/SagaData,System.Object>>(System.Linq.Expressions.Expression,System.Linq.Expressions.ParameterExpression[])}
 [36] = {Mono.Cecil.Cil.Instruction} {IL_0074: callvirt System.Void NServiceBus.ToSagaExpression`2<SagaDefinitionReaderTest/SimpleSaga/SagaData,System.Object>::ToSaga(System.Linq.Expressions.Expression`1<System.Func`2<!0,System.Object>>)}
 [37] = {Mono.Cecil.Cil.Instruction} {IL_0079: nop}
 [38] = {Mono.Cecil.Cil.Instruction} {IL_007a: ldarg.1}
 [39] = {Mono.Cecil.Cil.Instruction} {IL_007b: ldtoken System.String}
 [40] = {Mono.Cecil.Cil.Instruction} {IL_0080: call System.Type System.Type::GetTypeFromHandle(System.RuntimeTypeHandle)}
 [41] = {Mono.Cecil.Cil.Instruction} {IL_0085: ldstr "o"}
 [42] = {Mono.Cecil.Cil.Instruction} {IL_008a: call System.Linq.Expressions.ParameterExpression System.Linq.Expressions.Expression::Parameter(System.Type,System.String)}
 [43] = {Mono.Cecil.Cil.Instruction} {IL_008f: stloc.0}
 [44] = {Mono.Cecil.Cil.Instruction} {IL_0090: ldnull}
 [45] = {Mono.Cecil.Cil.Instruction} {IL_0091: ldtoken System.Object}
 [46] = {Mono.Cecil.Cil.Instruction} {IL_0096: call System.Type System.Type::GetTypeFromHandle(System.RuntimeTypeHandle)}
 [47] = {Mono.Cecil.Cil.Instruction} {IL_009b: call System.Linq.Expressions.ConstantExpression System.Linq.Expressions.Expression::Constant(System.Object,System.Type)}
 [48] = {Mono.Cecil.Cil.Instruction} {IL_00a0: ldc.i4.1}
 [49] = {Mono.Cecil.Cil.Instruction} {IL_00a1: newarr System.Linq.Expressions.ParameterExpression}
 [50] = {Mono.Cecil.Cil.Instruction} {IL_00a6: dup}
 [51] = {Mono.Cecil.Cil.Instruction} {IL_00a7: ldc.i4.0}
 [52] = {Mono.Cecil.Cil.Instruction} {IL_00a8: ldloc.0}
 [53] = {Mono.Cecil.Cil.Instruction} {IL_00a9: stelem.ref}
 [54] = {Mono.Cecil.Cil.Instruction} {IL_00aa: call System.Linq.Expressions.Expression`1<!!0> System.Linq.Expressions.Expression::Lambda<System.Func`2<System.String,System.Object>>(System.Linq.Expressions.Expression,System.Linq.Expressions.ParameterExpression[])}
 **[55] = {Mono.Cecil.Cil.Instruction} {IL_00af: callvirt NServiceBus.ToSagaExpression`2<!0,!!0> NServiceBus.SagaPropertyMapper`1<SagaDefinitionReaderTest/SimpleSaga/SagaData>::ConfigureMapping<System.String>(System.Linq.Expressions.Expression`1<System.Func`2<!!0,System.Object>>)}**
 [56] = {Mono.Cecil.Cil.Instruction} {IL_00b4: ldtoken SagaDefinitionReaderTest/SimpleSaga/SagaData}
 [57] = {Mono.Cecil.Cil.Instruction} {IL_00b9: call System.Type System.Type::GetTypeFromHandle(System.RuntimeTypeHandle)}
 [58] = {Mono.Cecil.Cil.Instruction} {IL_00be: ldstr "s"}
 [59] = {Mono.Cecil.Cil.Instruction} {IL_00c3: call System.Linq.Expressions.ParameterExpression System.Linq.Expressions.Expression::Parameter(System.Type,System.String)}
 [60] = {Mono.Cecil.Cil.Instruction} {IL_00c8: stloc.0}
 [61] = {Mono.Cecil.Cil.Instruction} {IL_00c9: ldloc.0}
 **[62] = {Mono.Cecil.Cil.Instruction} {IL_00ca: ldtoken System.String SagaDefinitionReaderTest/SimpleSaga/SagaData::get_Correlation()}**
 [63] = {Mono.Cecil.Cil.Instruction} {IL_00cf: call System.Reflection.MethodBase System.Reflection.MethodBase::GetMethodFromHandle(System.RuntimeMethodHandle)}
 [64] = {Mono.Cecil.Cil.Instruction} {IL_00d4: castclass System.Reflection.MethodInfo}
 [65] = {Mono.Cecil.Cil.Instruction} {IL_00d9: call System.Linq.Expressions.MemberExpression System.Linq.Expressions.Expression::Property(System.Linq.Expressions.Expression,System.Reflection.MethodInfo)}
 [66] = {Mono.Cecil.Cil.Instruction} {IL_00de: ldc.i4.1}
 [67] = {Mono.Cecil.Cil.Instruction} {IL_00df: newarr System.Linq.Expressions.ParameterExpression}
 [68] = {Mono.Cecil.Cil.Instruction} {IL_00e4: dup}
 [69] = {Mono.Cecil.Cil.Instruction} {IL_00e5: ldc.i4.0}
 [70] = {Mono.Cecil.Cil.Instruction} {IL_00e6: ldloc.0}
 [71] = {Mono.Cecil.Cil.Instruction} {IL_00e7: stelem.ref}
 [72] = {Mono.Cecil.Cil.Instruction} {IL_00e8: call System.Linq.Expressions.Expression`1<!!0> System.Linq.Expressions.Expression::Lambda<System.Func`2<SagaDefinitionReaderTest/SimpleSaga/SagaData,System.Object>>(System.Linq.Expressions.Expression,System.Linq.Expressions.ParameterExpression[])}
 [73] = {Mono.Cecil.Cil.Instruction} {IL_00ed: callvirt System.Void NServiceBus.ToSagaExpression`2<SagaDefinitionReaderTest/SimpleSaga/SagaData,System.String>::ToSaga(System.Linq.Expressions.Expression`1<System.Func`2<!0,System.Object>>)}
 [74] = {Mono.Cecil.Cil.Instruction} {IL_00f2: nop}
 [75] = {Mono.Cecil.Cil.Instruction} {IL_00f3: ret}
```

I hilighted the positions with ** 

It seems for simple mappings (which we assume anyway) we could detect the correlation property easily by seeking the ToSaga expression and then getting the SagaData::get_Property calls. Mono cecil seems to have all the info we need. Thoughts?

**Comment by SimonCropp** [comment]
Add some if statements in there and how would u determine the mapping?

**Comment by DavidBoike** [comment]
If an if statement is encountered, or the Saga has an intermediate base class before `Saga<T>`, then you'd have to bail out and throw, insisting on the attribute as a backup.

I think it's worth exploring divining correlation id out of the method as long as the code for the method strictly calls `mapper.ConfigureMapping<T>().ToSaga()` (multiple times allowed) and does nothing else. This would correctly cover every Saga I've ever written in my life.

We can't solve completely for the 100% case but that doesn't mean we can't explore a 97% solution.

**Comment by danielmarbach** [comment]
I think a dead simple convention would do it. For example you get all the getter property access on the saga data and distinct them. If the result is one element you use it, if not you throw at build time with the instruction to add the correlation property attribute. Like @DavidBoike said this covers must use cases

**Comment by SimonCropp** [comment]
>I think it's worth exploring divining correlation id out of the method as long as the code for the method strictly calls mapper.ConfigureMapping<T>().ToSaga() (multiple times allowed) and does nothing else. 

the problem is this is not possible. Take the following valid cases

 * dynamic code in the message part that executes arbitrary code
 * switching logic in the base class
 * calls to other libs that we do not have the IL for

There are many other valid edge case that they can do with the current core `ConfigureMapping` API. having someone use the sql persister until they suddenly have friction down the line where they are doing something valid is not a great experience. 

Also it is likely a consumer of the sql persister will need to use the SqlSagaAttribute for other config options. example to control the table name for a saga https://docs.particular.net/nservicebus/sql-persistence/saga#table-structure-table-name

**Comment by SimonCropp** [comment]
> if...  the Saga has an intermediate base class before Saga<T>, then you'd have to bail out and throw, insisting on the attribute as a backup.

This is also not possible at the IL level. so as to not overly impact build time we dont load and parse the IL of dependencies. the only way you can detect "a class inherits from Saga<T>" is to walk the class hierarchy of every type, including walking into dependencies.

**Comment by SimonCropp** [comment]
given how often this question has been asked i have added to the doco https://docs.particular.net/nservicebus/sql-persistence/saga#requirement-for-the-sqlsagaattribute

**Comment by danielmarbach** [comment]
So what if a user adds the attribute to his base which inherits from
SqlSaga? Don't you have the same problem then?

so the arguments in TLDR form are:

Because users might do weird edge cases in mapping (which I've not soon
yet) and because advanced scenarios like overriding table name might be
required we diverge by default from the standard saga model.

I can't say I'm convinced. Given though you have much more NSB and saga
experience I highly respect the decision and leave it at that.

**Comment by SimonCropp** [comment]
> So what if a user adds the attribute to his base which inherits from
SqlSaga? Don't you have the same problem then?

It is a non-inherited attribute. i will add that to the doco

> Because users might do weird edge cases in mapping (which I've not soon
yet) and because advanced scenarios like overriding table name might be
required we diverge by default from the standard saga model.

the problem is that even though they are rare we cant detect them as edge cases and hence cannot exclude them. you are essentially asking for guess and gamble on the fact that someone wont do something strange (but supported by NSB)

**Comment by udidahan** [comment]
I can't imagine a single scenario where someone would need to do anything other than ConfigureMapping calls from within the ConfigureHowToFindSaga method.

**Comment by danielmarbach** [comment]
@udidahan Exactly my point I was trying to make. Though @SimonCropp is right by saying the API https://github.com/Particular/NServiceBus/blob/develop/src/NServiceBus.Core/Sagas/SagaPropertyMapper.cs#L27 could be abused to put any arbitrary code into it. In the later code we check whether what the expression returned is really a property https://github.com/Particular/NServiceBus/blob/d462080b0efa6609f0f92d4e192d760142ac47c2/src/NServiceBus.Core/Sagas/SagaMetadata.cs#L374 but still technically it is possible to add arbitrary code there. Though I think this is a use case which is rarely abused.

**Comment by danielmarbach** [comment]
For example if you try to do anything fancy then the following happens in v6

![image](https://cloud.githubusercontent.com/assets/174258/23600385/ae58a946-0246-11e7-8bda-f6fbe72326b6.png)

**Comment by danielmarbach** [comment]
The only way you get the code compiling is to do this

```
            protected override void ConfigureHowToFindSaga(SagaPropertyMapper<SagaData> mapper)
            {
                mapper.ConfigureMapping<SomeMessage>(m => m.SomeProperty).ToSaga(s =>MappDynamically(s));
            }

            static object MappDynamically(SagaData data)
            {
                if (data.SomeId == Guid.Empty)
                {
                    return Guid.NewGuid();
                }

                return data.SomeId;
            }
```

but then the core blows up with the following exception

```
NServiceBus.Core.Tests.Sagas.TypeBasedSagas.SagaMetadataCreationTests.VerifyComplexMapping

System.ArgumentException : Not a member access
Parameter name: member
   at NServiceBus.Reflect`1.GetMemberInfo(Expression member, Boolean checkForSingleDot) in C:\p\NServiceBus\src\NServiceBus.Core\Utils\Reflection\Reflect.cs:line 69
   at NServiceBus.Sagas.SagaMetadata.SagaMapper.NServiceBus.IConfigureHowToFindSagaWithMessage.ConfigureMapping[TSagaEntity,TMessage](Expression`1 sagaEntityProperty, Expression`1 messageExpression) in C:\p\NServiceBus\src\NServiceBus.Core\Sagas\SagaMetadata.cs:line 370
   at NServiceBus.ToSagaExpression`2.ToSaga(Expression`1 sagaEntityProperty) in C:\p\NServiceBus\src\NServiceBus.Core\Sagas\ToSagaExpression.cs:line 30
   at NServiceBus.Core.Tests.Sagas.TypeBasedSagas.SagaMetadataCreationTests.SagaWithComplexMappingExpression.ConfigureHowToFindSaga(SagaPropertyMapper`1 mapper) in C:\p\NServiceBus\src\NServiceBus.Core.Tests\Sagas\SagaMetadataCreationTests.cs:line 724
   at NServiceBus.Saga`1.ConfigureHowToFindSaga(IConfigureHowToFindSagaWithMessage sagaMessageFindingConfiguration) in C:\p\NServiceBus\src\NServiceBus.Core\Sagas\SagaT.cs:line 36
   at NServiceBus.Sagas.SagaMetadata.Create(Type sagaType, IEnumerable`1 availableTypes, Conventions conventions) in C:\p\NServiceBus\src\NServiceBus.Core\Sagas\SagaMetadata.cs:line 168
   at NServiceBus.Sagas.SagaMetadata.Create(Type sagaType) in C:\p\NServiceBus\src\NServiceBus.Core\Sagas\SagaMetadata.cs:line 143
   at NServiceBus.Core.Tests.Sagas.TypeBasedSagas.SagaMetadataCreationTests.Foo() in C:\p\NServiceBus\src\NServiceBus.Core.Tests\Sagas\SagaMetadataCreationTests.cs:line 228


```
